In [6]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [7]:
pulsars=pd.read_csv("C:\\Users\\erike\\OneDrive//Python-Class//pulsar_stars.csv")

In [8]:
p1=pulsars.rename(columns={" Mean of the integrated profile":"Profile_Mean",
                           " Standard deviation of the integrated profile":"Profile_STD",
                           " Excess kurtosis of the integrated profile":"Profile_Excess_Kurtosis",
                           " Skewness of the integrated profile":"Profile_Skewness",
                           " Mean of the DM-SNR curve":"DM-SNR_Curve_Mean",
                           " Standard deviation of the DM-SNR curve":"DM-SNR_Curve_STD",
                           " Excess kurtosis of the DM-SNR curve":"DM-SNR_Curve_Excess_Kurtosis",
                           " Skewness of the DM-SNR curve":"DM-SNR_Curve_Skewness"})

In [9]:
df=p1.astype({'target_class':'object'})

In [10]:
df.drop_duplicates(keep='first')

,Profile_Mean,Profile_STD,Profile_Excess_Kurtosis,Profile_Skewness,DM-SNR_Curve_Mean,DM-SNR_Curve_STD,DM-SNR_Curve_Excess_Kurtosis,DM-SNR_Curve_Skewness,target_class
0,140.562500,55.683782,-0.234571,-0.699648,3.199833,19.110426,7.975532,74.242225,0
1,102.507812,58.882430,0.465318,-0.515088,1.677258,14.860146,10.576487,127.393580,0
2,103.015625,39.341649,0.323328,1.051164,3.121237,21.744669,7.735822,63.171909,0
3,136.750000,57.178449,-0.068415,-0.636238,3.642977,20.959280,6.896499,53.593661,0
4,88.726562,40.672225,0.600866,1.123492,1.178930,11.468720,14.269573,252.567306,0
...,...,...,...,...,...,...,...,...,...
17893,136.429688,59.847421,-0.187846,-0.738123,1.296823,12.166062,15.450260,285.931022,0
17894,122.554688,49.485605,0.127978,0.323061,16.409699,44.626893,2.945244,8.297092,0
17895,119.335938,59.935939,0.159363,-0.743025,21.430602,58.872000,2.499517,4.595173,0
17896,114.507812,53.902400,0.201161,-0.024789,1.946488,13.381731,10.007967,134.238910,0
17897,57.062500,85.797340,1.406391,0.089520,188.306020,64.712562,-1.597527,1.429475,0

In [12]:
df.isna().sum()

Profile_Mean                    0
Profile_STD                     0
Profile_Excess_Kurtosis         0
Profile_Skewness                0
DM-SNR_Curve_Mean               0
DM-SNR_Curve_STD                0
DM-SNR_Curve_Excess_Kurtosis    0
DM-SNR_Curve_Skewness           0
target_class                    0
dtype: int64

In [ ]:
# We are not handling outliers, because this data is not normal, and also we are looking for outliers.

In [ ]:
#One Hot encoding is also not being used here because with the exception of target class everything's numeric.
#And target class is just 0 or 1 already.

In [13]:
def remove_collin(df, target, threshold):
    global y
    y=df[target]
    df.drop(target, axis=1, inplace=True)
    corr=df.corr(numeric_only=True)
    upper=corr.where(np.triu(np.ones(corr.shape), k=1).astype('bool'))
    dropped=[column for column in upper.columns if any(abs(upper[column]>threshold))]
    print('Dropping: ',dropped, '\n')
    df.drop(dropped, axis=1, inplace=True)
    return df

In [14]:
remove_collin(df, 'target_class',.6)

Dropping:  ['Profile_Skewness', 'DM-SNR_Curve_STD', 'DM-SNR_Curve_Skewness']

,Profile_Mean,Profile_STD,Profile_Excess_Kurtosis,DM-SNR_Curve_Mean,DM-SNR_Curve_Excess_Kurtosis
0,140.562500,55.683782,-0.234571,3.199833,7.975532
1,102.507812,58.882430,0.465318,1.677258,10.576487
2,103.015625,39.341649,0.323328,3.121237,7.735822
3,136.750000,57.178449,-0.068415,3.642977,6.896499
4,88.726562,40.672225,0.600866,1.178930,14.269573
...,...,...,...,...,...
17893,136.429688,59.847421,-0.187846,1.296823,15.450260
17894,122.554688,49.485605,0.127978,16.409699,2.945244
17895,119.335938,59.935939,0.159363,21.430602,2.499517
17896,114.507812,53.902400,0.201161,1.946488,10.007967
17897,57.062500,85.797340,1.406391,188.306020,-1.597527

In [15]:
y.shape

(17898,)

In [16]:
df.shape

(17898, 5)

In [18]:
x=df

In [19]:
df.shape

(17898, 5)

In [20]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=518)

In [21]:
x_train.shape, y_test.shape

((12528, 5), (5370,))

In [ ]:
#x_train ect is for no missing values for some modeling,
#There were no missing values so no boosting set.
#No scaling because the units here are all the same across the board.
#_p denotes this is the pulsar dataset

In [23]:
x_train.to_csv('x_train_p.csv',index=False) 
y_train.to_csv('y_train_p.csv',index=False)
x_test.to_csv('x_test_p.csv',index=False) 
y_test.to_csv('y_test_p.csv',index=False)